language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - postgresql

before_script:
  - psql -c 'create database sassyboot_testdb;' -U postgres

script:
  - ./gradlew clean test
