server:
  servlet:
    context-path: /
  port: 7800

management:
  port: 7900
  security.enabled: true

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql : true
  datasource:
    url: jdbc:postgresql://localhost:5432/sassyboot
  http:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  session:
    store-type: redis


logging:
  level:
    org:
      springframework:
        security: ERROR


app:
  security:
    csrf-token-header-name: X-CSRF-TOKEN
    csrf-token-cookie-name: XSRF-TOKEN
    auth-token-header-name: X-AUTH-TOKEN