-- liquibase formatted sql

-- changeset chandrakanta:role_table
CREATE TABLE ROLE (
    ID UUID NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    DISPLAY_NAME VARCHAR(1024) NOT NULL,
    DESCRIPTION VARCHAR(4096),
    SUBSCRIPTION_ID UUID,
    IS_SYS_ROLE BOOLEAN NOT NULL,
    IS_READ_ONLY BOOLEAN DEFAULT FALSE NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT ROLE_PKEY PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UNQ_SYS_ROLE_NAME ON ROLE(LOWER(NAME)) WHERE SUBSCRIPTION_ID IS  NULL;
CREATE UNIQUE INDEX UNQ_SUBSCRIPTION_ROLE_NAME ON ROLE(LOWER(NAME), SUBSCRIPTION_ID) WHERE SUBSCRIPTION_ID IS NOT NULL;

INSERT INTO ROLE (ID, NAME, DISPLAY_NAME, DESCRIPTION, IS_SYS_ROLE, IS_READ_ONLY, IS_ACTIVE)
VALUES ('9D03CEAA-C582-11E7-B806-0758598C7C0F',
        'ADMIN',
        'ADMIN',
        'ADMINISTRATOR. USER WITH THIS ROLE CAN PERFORM ALL TASKS.',
        'FALSE', 'TRUE', 'TRUE');

INSERT INTO ROLE (ID, NAME, DISPLAY_NAME, DESCRIPTION, IS_SYS_ROLE, IS_READ_ONLY, IS_ACTIVE)
VALUES ('9432F028-F809-496B-8FBE-6EF9166069DF',
        'SYSTEM_ADMIN', 'SYSTEM ADMIN',
        'SYSTEM ADMINISTRATOR. USER WITH THIS ROLE CAN PERFORM ALL TASK IN APPLICATION LEVEL.',
         'TRUE', 'TRUE', 'TRUE');
-- rollback DROP TABLE ROLE

-- changeset chandrakanta:permission_table
CREATE TABLE PERMISSION (
    ID UUID NOT NULL,
    NAME VARCHAR(2048) NOT NULL,
    DISPLAY_NAME VARCHAR(2048) NOT NULL,
    DESCRIPTION VARCHAR(4096),
    PARENT_PERMISSION UUID,
    CONSTRAINT PERMISSION_PKEY PRIMARY KEY (ID)
);
-- rollback DROP TABLE PERMISSION


-- changeset chandrakanta:role_permission_relationship
CREATE TABLE ROLE_HAS_PERMISSIONS (
    ROLE_ID UUID NOT NULL,
    PERMISSION_ID UUID NOT NULL
);

CREATE UNIQUE INDEX UNQ_ROLE_HAS_PERMISSIONS ON ROLE_HAS_PERMISSIONS(ROLE_ID, PERMISSION_ID);
-- rollback DROP TABLE ROLE_HAS_PERMISSIONS


-- changeset chandrakanta:role_can_grant_role_table
CREATE TABLE ROLE_CAN_GRANT_ROLES (
    ROLE_ID UUID NOT NULL,
    CAN_GRANT_ROLE UUID NOT NULL
);

CREATE UNIQUE INDEX UNQ_ROLE_CAN_GRANT_ROLE ON ROLE_CAN_GRANT_ROLES(ROLE_ID, CAN_GRANT_ROLE);
-- rollback DROP TABLE ROLE_CAN_GRANT_ROLES

-- changeset chandrakanta:sbt_user_table
CREATE TABLE SBT_USER (
    ID UUID NOT NULL,
    EMAIL_ID VARCHAR(1024) NOT NULL,
    MOBILE_NO VARCHAR(20),
    PASSWORD TEXT NOT NULL,
    NAME VARCHAR(2048) NOT NULL,
    FAILED_LOGIN_ATTEMPTED SMALLINT DEFAULT 0 NOT NULL,
    APP_ROLE UUID,
    CONSTRAINT SBT_USER_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_USER_APP_ROLE FOREIGN KEY (APP_ROLE) REFERENCES ROLE(ID)
);

INSERT INTO SBT_USER (ID, EMAIL_ID, MOBILE_NO, PASSWORD, NAME, APP_ROLE)
VALUES (
    'b516e3aa-a3af-11e7-bbd2-63ad024569ce',
    'admin@sassyboot.com','5708693854',
    '$2a$10$ooovkewokxduxzmrdmbsu.slfsvcxsclfxjt0j2mzicno201ocgtk', -- encoded('password')
    'sassyboot admin', '9432f028-f809-496b-8fbe-6ef9166069df'
);
-- rollback DROP TABLE SBT_USER
