-- liquibase formatted sql
-- changeset chandrakanta:subscription_table
CREATE TYPE CUSTOMER_TYPE AS ENUM('INDIVIDUAL','ORGANISATION');

CREATE TABLE SUBSCRIPTION (
    ID UUID NOT NULL, SUBSCRIBED_ON TIMESTAMP WITH TIME ZONE NOT NULL,
    NAME VARCHAR(128) NOT NULL, CUSTOMER_TYPE CUSTOMER_TYPE NOT NULL,
    OWNER_ID UUID, ORG_ID UUID, IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_BY UUID,
    CONSTRAINT SUBSCRIPTION_PKEY PRIMARY KEY (ID)
);
-- rollback DROP TABLE SUBSCRIPTION

-- changeset chandrakanta:subscription_user_table
CREATE TABLE SUBSCRIPTION_USER (
    ID UUID NOT NULL, SUBSCRIPTION_ID UUID NOT NULL,
    USER_ID UUID NOT NULL, ROLE_ID UUID NOT NULL,
    CONSTRAINT SUBSCRIPTION_USER_PKEY PRIMARY KEY (ID)
);
-- rollback DROP TABLE SUBSCRIPTION_USER